version: '3'

services:
  app:
    build: 
      context: ./
      args:
        WEB_USER_ID: 33
        WEB_USER_NAME: www-data
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS=
    working_dir: /var/www/vue
    expose:
      - 8000
      - 8080
    volumes: 
      - .:/var/www/vue

